include(joinpath(@__DIR__, "estonian.jl"))
include(joinpath(@__DIR__, "time_learn_train.jl"))
include(joinpath(@__DIR__, "time_learn_val.jl"))
include(joinpath(@__DIR__, "time_build_train.jl"))
include(joinpath(@__DIR__, "time_build_val.jl"))